<template>
  <div class="loader mx-auto d-flex justify-content-center align-items-start">
    <div class="loadingio-spinner-spinner-rxa35mtvk7e">
      <div class="ldio-2a1gc6ffigl">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </div>
</template>

<script setup></script>

<style lang="scss" type="text/css">
@keyframes ldio-2a1gc6ffigl {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
.ldio-2a1gc6ffigl div {
  left: 88.825px;
  top: 55.165000000000006px;
  position: absolute;
  animation: ldio-2a1gc6ffigl linear 1.1111111111111112s infinite;
  background: #a8a8a8;
  width: 9.350000000000001px;
  height: 20.57px;
  border-radius: 4.675000000000001px / 6.7881px;
  transform-origin: 4.675000000000001px 38.335px;
}
.ldio-2a1gc6ffigl div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -1.0101010101010102s;
  background: #a8a8a8;
}
.ldio-2a1gc6ffigl div:nth-child(2) {
  transform: rotate(32.72727272727273deg);
  animation-delay: -0.9090909090909091s;
  background: #a8a8a8;
}
.ldio-2a1gc6ffigl div:nth-child(3) {
  transform: rotate(65.45454545454545deg);
  animation-delay: -0.8080808080808081s;
  background: #a8a8a8;
}
.ldio-2a1gc6ffigl div:nth-child(4) {
  transform: rotate(98.18181818181819deg);
  animation-delay: -0.7070707070707071s;
  background: #a8a8a8;
}
.ldio-2a1gc6ffigl div:nth-child(5) {
  transform: rotate(130.9090909090909deg);
  animation-delay: -0.6060606060606061s;
  background: #a8a8a8;
}
.ldio-2a1gc6ffigl div:nth-child(6) {
  transform: rotate(163.63636363636363deg);
  animation-delay: -0.5050505050505051s;
  background: #a8a8a8;
}
.ldio-2a1gc6ffigl div:nth-child(7) {
  transform: rotate(196.36363636363637deg);
  animation-delay: -0.40404040404040403s;
  background: #a8a8a8;
}
.ldio-2a1gc6ffigl div:nth-child(8) {
  transform: rotate(229.0909090909091deg);
  animation-delay: -0.30303030303030304s;
  background: #a8a8a8;
}
.ldio-2a1gc6ffigl div:nth-child(9) {
  transform: rotate(261.8181818181818deg);
  animation-delay: -0.20202020202020202s;
  background: #a8a8a8;
}
.ldio-2a1gc6ffigl div:nth-child(10) {
  transform: rotate(294.54545454545456deg);
  animation-delay: -0.10101010101010101s;
  background: #a8a8a8;
}
.ldio-2a1gc6ffigl div:nth-child(11) {
  transform: rotate(327.27272727272725deg);
  animation-delay: 0s;
  background: #a8a8a8;
}
.loadingio-spinner-spinner-rxa35mtvk7e {
  width: toRem(165);
  height: toRem(165);
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-2a1gc6ffigl {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-2a1gc6ffigl div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
